name: Github Actions Example Cron
run-name: ${{github.actor}} está testando o Github Actions
on:
  schedule:
    - cron: '0 13 * * 5'
jobs:
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Esta pipeline está rodando todas as sextas-feiras as 13h"



